name: chopper
description: Chopper is an http client generator using source_gen and inspired from retrofit
version: 3.0.1+2
homepage: https://hadrien-lejard.gitbook.io/chopper
repository: https://github.com/lejard-h/chopper
author: Hadrien Lejard <hadrien.lejard@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  http: ">=0.11.0 <1.0.0"
  meta: ^1.1.2
  logging: ^0.11.3

dev_dependencies:
  test: ^1.3.0
  build_runner: ^1.2.2
  build_test:
  coverage: ^0.13.6
  test_coverage: ^0.4.1
  http_parser: ^3.1.3
  pedantic: ^1.9.0
  chopper_generator:
    path: ../chopper_generator